name: Test

on: [push, workflow_dispatch]

jobs:
  metrics:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout main branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Checkout data branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: "data"
          path: "data"

      - uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1

      - name: Install dependencies
        run: uv sync

      - name: Generate metrics
        run: |
          uv run gametrack-data metrics \
            --input-filename data/games.csv
